### ISSUE TITLE
External Links

### ISSUE THREAD

**Issue by jmwright** [matthewmaier/platyvue#2]
How would I include a link to an external image on something like Flickr? Does it get added as info to a record the same way a title does? How would this be rendered in the network graph, or would it even?

**Comment by matthewmaier** [comment]
The intention is to leverage hyperlinking as much as possible. Most files
should be in the same folder (or folder structure) as the .plat file, but
if something is located somewhere else Platyvue will just try to retrieve
it. The basic pattern I've worked out at this point for including arbitrary
information is a new record with a name for the array key and the data to
go into it. So for something like your example I'm thinking
array[document][record][file]http://www.flickr.com/whatever.png

I think there are some categories of information that make sense to include
by default once we get to that point. For example, an icon (small image),
title (short unique description), body (paragraph), figure (descriptive
picture), etc.

At this point, my assumption is that if Platyvue is trying to display the
info associated with a step and it runs across a URL to an image file it
will just try to display the image; that's what Livecode does anyway. It
just sends the request to the server instead of to the local drive.

**Comment by jmwright** [comment]
I have a feeling that hyperlinking between Platypus files will work a little differently than hyperlinking between Platypus tables/documents in databases (like MongoDB). That's maybe something to keep in mind as things progress.
